# Generated by Django 2.2.1 on 2019-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmerApp', '0002_auto_20190501_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledata',
            name='days_after_sowing',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
